name: Sema CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            targets: "x86_64-unknown-linux-gnu x86_64-pc-windows-gnu"
            deps: "sudo apt-get update && sudo apt-get install -y protobuf-compiler gcc-mingw-w64"
          - os: macos-latest
            targets: "x86_64-apple-darwin aarch64-apple-darwin"
            deps: "brew install protobuf"
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: ${{ matrix.deps }}
    
    - name: Install Rust toolchain and targets
      run: |
        for target in ${{ matrix.targets }}; do
          rustup target add $target
        done
    
    - name: Build/Check for all targets
      run: |
        for target in ${{ matrix.targets }}; do
          if [ "${{ github.event_name }}" = "release" ]; then
            cargo build --release --target $target
          else
            cargo check --release --target $target
          fi
        done
    
    - name: Upload release artifacts
      if: github.event_name == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: sema-${{ matrix.os }}
        path: |
          target/*/release/sema
          target/*/release/sema.exe
        if-no-files-found: ignore
